var obj = { propriedade_1:   valor_1,   // propriedade_# pode ser um identificador...
            propriedade_2:   valor_2,   // ou um numero...
            // ...,
            propriedade_n: valor_n }; // ou uma string

            console.log(obj.propriedade_1);